### ISSUE TITLE
Error on Ubuntu below. On home dedicated linux box.

### ISSUE THREAD

**Issue by jshousephd** [demis001/raslpipe#9]
john@john-linux:/etc/apt$ sudo add-apt-repository ppa:ubuntu-toolchain-r/testsudo && sudo apt-get update && sudo apt-get install gcc-5
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 102, in _get_https_content_py3
    lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 503, in error
    result = self._call_chain(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 327, in get_ppa_info
    ret = get_ppa_info_from_lp(user, ppa)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 92, in get_ppa_info_from_lp
    return get_info_from_lp(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
    return _get_https_content_py3(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 108, in _get_https_content_py3
    raise PPAException("Error reading %s: %s" % (lp_url, reason), e)
softwareproperties.ppa.PPAException: 'Error reading https://launchpad.net/api/1.0/~ubuntu-toolchain-r/+archive/ubuntu/testsudo: Not Found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 393, in shortcut_handler
    return PPAShortcutHandler(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 356, in **init**
    info = get_ppa_info(self.shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 339, in get_ppa_info
    _get_suggested_ppa_message(user, ppa))
softwareproperties.shortcuts.ShortcutException: Cannot add PPA: 'ppa:~ubuntu-toolchain-r/ubuntu/testsudo'.
The team named '~ubuntu-toolchain-r' has no PPA named 'ubuntu/testsudo'
Please choose from the following available PPAs:
- 'aarch64':  AArch64
- 'glibc':  (E)Glibc test builds
- 'power8':  POWER8
- 'ppa':  Toolchain builds
- 'python3':  Python3
- 'test':  Toolchain test builds
  Error: 'ppa:ubuntu-toolchain-r/testsudo' invalid

**Comment by demis001** [comment]
Can you paste the version of Ubuntu?

You may try this in terminal:

`lsb_release -a`

Or System Settings -> Details

**Comment by akadrhouse** [comment]
It is at home, and I can't get the remote terminal to the machine to work. I'm pretty sure it is 16.04; I know it it 16.  Xenial is the release name.

**Comment by demis001** [comment]
Thanks!  I see it has Python 3.2, I never tried on that. I will load Xenial Xerus operating system and see if I get the same error.

**Comment by demis001** [comment]
I have completed the a test on Ubuntu 16.04 and updated install docs. You only need to  execute the first line of the system requirement. Don't need the second line.

[https://github.com/demis001/raslpipe/blob/master/docs/source/install.rst](url)

![image](https://cloud.githubusercontent.com/assets/8713514/16590843/3bfb7fc2-42a7-11e6-8f0b-f04c4f1efc70.png)
